package com.biit.appointment.core.providers;

import com.biit.appointment.core.exceptions.InvalidParameterException;
import com.biit.appointment.persistence.entities.Appointment;
import com.biit.appointment.persistence.entities.AppointmentStatus;
import com.biit.appointment.persistence.entities.ExaminationType;
import com.biit.appointment.persistence.entities.Recurrence;
import com.biit.appointment.persistence.repositories.AppointmentRepository;
import com.biit.appointment.persistence.repositories.RecurrenceRepository;
import com.biit.server.providers.ElementProvider;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

@Service
public class AppointmentProvider extends ElementProvider<Appointment, Long, AppointmentRepository> {

    private final RecurrenceRepository recurrenceRepository;


    public AppointmentProvider(AppointmentRepository repository, RecurrenceRepository recurrenceRepository) {
        super(repository);
        this.recurrenceRepository = recurrenceRepository;
    }


    /**
     * Finds all appointments from an organization.
     *
     * @param organizerId the organizer of the appointment.
     * @return a list of appointments.
     */
    public List<Appointment> findByOrganizerId(Long organizerId) {
        if (organizerId == null) {
            throw new InvalidParameterException(this.getClass(), "You must select an organization!");
        }
        return getRepository().findByOrganizerId(organizerId);
    }


    /**
     * Find all appointments that matches the search parameters. If startTime and endTime is defined, will search any appointment inside this range.
     *
     * @param organizationId      the organization of the parameters (can be null for any organization).
     * @param organizerId         who must resolve the appointment (can be null for any organizer).
     * @param attendee            who attend the meeting.
     * @param examinationTypes    a collection of types of the appointment (can be null for any type).
     * @param appointmentStatuses the status of the appointment (can be null for any status).
     * @param lowerTimeBoundary   the lower limit on time for searching an appointment  (can be null for no limit).
     * @param upperTimeBoundary   the upper limit on time for searching an appointment  (can be null for no limit).
     * @param deleted             the appointment is deleted or not.
     * @return a list of appointments.
     */
    public List<Appointment> findBy(Long organizationId, Long organizerId, Long attendee, Collection<ExaminationType> examinationTypes,
                                    Collection<AppointmentStatus> appointmentStatuses,
                                    LocalDateTime lowerTimeBoundary, LocalDateTime upperTimeBoundary, Boolean deleted) {
        final List<Recurrence> recurrences = recurrenceRepository.findBy(organizationId, organizerId, examinationTypes, lowerTimeBoundary, upperTimeBoundary);
        final List<Appointment> appointments = getRepository().findBy(organizationId, organizerId, attendee, examinationTypes, appointmentStatuses,
                lowerTimeBoundary, upperTimeBoundary, deleted);
        //Add appointments generated by recurrence.
        recurrences.forEach(recurrence ->
                //Gets all matching dates.
                recurrence.getMatches(lowerTimeBoundary, upperTimeBoundary).forEach(matchingDate -> {
                    //Generate a new appointment for each matching date.
                    //Not if it has an appointment already generated on this date. As already got from appointmentRepository.
                    if (recurrence.getAppointment(matchingDate) == null) {
                        appointments.add(Appointment.of(recurrence.getAppointments().get(0),
                                matchingDate.atTime(recurrence.getAppointments().get(0).getStartTime().toLocalTime())));
                    }
                }));
        Collections.sort(appointments);
        return appointments;
    }


    /**
     * Counts the total appointments that matches the search parameters. If startTime and endTime is defined, will search any appointment inside this range.
     *
     * @param organizationId      the organization of the parameters (can be null for any organization).
     * @param organizerId         who must resolve the appointment (can be null for any organizer).
     * @param attendee            who attend the meeting.
     * @param examinationTypes    a collection of types of the appointment (can be null for any type).
     * @param appointmentStatuses the status of the appointment (can be null for any status).
     * @param lowerTimeBoundary   the lower limit on time for searching an appointment  (can be null for no limit).
     * @param upperTimeBoundary   the upper limit on time for searching an appointment  (can be null for no limit).
     * @param deleted             the appointment is deleted or not.
     * @return the total number of appointments
     */
    public long count(Long organizationId, Long organizerId, Long attendee, Collection<ExaminationType> examinationTypes,
                      Collection<AppointmentStatus> appointmentStatuses,
                      LocalDateTime lowerTimeBoundary, LocalDateTime upperTimeBoundary, Boolean deleted) {
        final AtomicLong appointments = new AtomicLong(getRepository().count(organizationId, organizerId, attendee, examinationTypes, appointmentStatuses,
                lowerTimeBoundary, upperTimeBoundary, deleted));
        final List<Recurrence> recurrences = recurrenceRepository.findBy(organizationId, organizerId, examinationTypes, lowerTimeBoundary, upperTimeBoundary);
        recurrences.forEach(recurrence -> appointments.addAndGet(recurrence.getMatches(lowerTimeBoundary, upperTimeBoundary).size()));
        return appointments.get();
    }


    /**
     * Checks if the appointment overlaps with any different appointment.
     *
     * @param appointment the appointment to check
     * @return if overlaps with any other appointment apart from the input.
     */
    public boolean overlaps(Appointment appointment) {
        return getRepository().overlaps(appointment) > 0;
    }

}
